Fix critical bug in jparse/test_jparse/Makefile
ioccc-src/mkiocccentry pull request #1031
Opened 2024-11-18 20:25 UTC by xexyl

For linux the test_jparse/Makefile needs -lm for util_test. Without this it will not compile and this will cause a big problem with using the library here.

Other improvements and bug fixes in jparse were made as well that might as well be synced up.

2024-11-18 20:27 UTC, xexyl commented
Sorry about this. I know you wanted to not have any more commits but this seems like a critical problem. I know multiple linux distros do not include the maths library by default. It seems when `util_test` was added (a good thing to have) it broke compilation in linux.

But at least some bugs were fixed and other improvements were made, I guess.

2024-11-19 03:18 UTC, lcn2 commented
> Sorry about this. I know you wanted to not have any more commits but this seems like a critical problem. I know multiple linux distros do not include the maths library by default. It seems when `util_test` was added (a good thing to have) it broke compilation in linux.
> 
> 
> 
> But at least some bugs were fixed and other improvements were made, I guess.

We will need to do some testing to evaluate and determine the impact.

2024-11-19 03:36 UTC, lcn2 requested changes
> Other improvements and bug fixes in jparse were made as well that might as well be synced 

This isn't just adding a link to some maths library for some t st code.  This PR changes 18 files!

As such this PR is changing too much.

Also under what Linux distribution(s) does the lack of -lm break compiling?

2024-11-19 13:42 UTC, xexyl commented
The interesting thing: I actually thought of the first part. Will fix soon. Probably all I can do today. 

As far as which systems: at least Rocky but it very likely is also fedora. It also doesn't link in the maths library.

2024-11-19 13:44 UTC, xexyl commented
I don't think you need to  issue a new release. 

I almost didn't sync the whole thing but against better judgement I did. 


Nonetheless I will close this soon and in a bit open a new one.

2024-11-19 13:49 UTC, xexyl commented
I wonder if the workflows can use Red Hat systems. If so it might help find these problems sooner.  

Will look into that. Closing this and will see if I can figure out why it even needs it. In any case I will open a new pull request with a fix. The `-lm` is probably the smallest change though. 

Closing.

2024-11-19 13:50 UTC, closed without merging

2024-11-19 13:51 UTC, xexyl commented
Okay booting laptop up and will look at this then. 

Thanks! 

I agree with you btw: I did almost only sync the Makefile mod. 

Hope you're sleeping well!

2024-11-19 14:02 UTC, xexyl commented
Unfortunately I had accidentally committed to master. This means that some other changes might be added unless I can figure out how to do this. I think I have to find out when the last commit occurred in jparse before the code freeze here and then pull that in the clone here. Then I can just sync the test_jparse/Makefile here. I'll look into that in a little while.

2024-11-19 14:03 UTC, xexyl commented
Oh ... I forgot the `.git` subdirectory is not synced. I have to come up with something else instead. Hmm ...

2024-11-19 14:07 UTC, xexyl commented
I have an idea. I'll clone my fork on the server and then do a commit that way. Will have to configure so I can push but that's not a problem. Will fix soon.

2024-11-19 14:11 UTC, xexyl commented
That might not work either ... since it wants the master branch :(

2024-11-19 14:17 UTC, xexyl commented
I am sorry but the only thing I can think of is for you to add the change. Then when I pull from the mkiocccentry repo directly it will overwrite my master branch (well you know what I mean).

So the change necessary is:

```diff
b387e32b0a66d jparse/test_jparse/Makefile 
diff --git a/jparse/test_jparse/Makefile b/jparse/test_jparse/Makefile
index 49a092b5c680617c05683049c59389f1e32a7fe6..9ac7ab6bef3055afdfed67f0a369a559149e20eb 100644
--- a/jparse/test_jparse/Makefile
+++ b/jparse/test_jparse/Makefile
@@ -449,11 +449,11 @@ util_test.c: ../util.c
 
 util_test.o: util_test.c
        ${CC} ${CFLAGS} -DUTIL_TEST util_test.c -c
 
 util_test: util_test.o ../libjparse.a
-   ${CC} ${CFLAGS} $^ -o $@ ${LD_DIR2} -ldbg -ldyn_array
+ ${CC} ${CFLAGS} $^ -o $@ ${LD_DIR2} -ldbg -ldyn_array -lm
```

Otherwise multiple Red Hat systems will not be able to compile the mkiocccentry/jparse directory.

Sorry. I can't think of another way except for deleting my fork but I'd really rather not do that. Maybe I can come up with something else sometime and maybe even tomorrow (today seems unlikely) but not today. I mean I could checkout the code freeze release but it doesn't seem to want to work :(

2024-11-19 14:20 UTC, xexyl commented
I will test something but if not I'm afraid you're going to have to do it. Stay tuned!

2024-11-19 14:36 UTC, xexyl commented
It looks like the idea will still require a merge (due to GitHub mis-feature) of the other commits from yesterday. I have one more idea and if it fails you'll have to make the change, else Red Hat systems probably can't compile the code due to the util_test not working (even though util.o does .. ah maybe that's why?).

2024-11-19 14:47 UTC, xexyl commented
Tested one more idea that should (I think) undo the changes on my master branch and then apply to this repo which would mean the changes in the code would not be applied (in the end).

Otherwise you'll have to apply the diff. Sorry.

2024-11-19 15:08 UTC, xexyl commented
You're never going to believe this.

It was because of a makefile.local file!

All of this because of that ... well at least the problem is resolved there. My clone is messed up and I might have to wait on another commit before that can be resolved but at least this is resolved.

2024-11-19 15:12 UTC, xexyl commented
I also know why the changes did not go through here. It was because it went to the jparse repo itself.

Will try undoing that one.

2024-11-19 15:23 UTC, xexyl commented
Everything in both repos should be fixed now, thankfully. Hope you have a great day!